# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0031_auto_20151117_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
