# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0032_timelineday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='section',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='default_section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
